apiVersion: v1
kind: ConfigMap
metadata:
  name: priceguard-config
  namespace: priceguard
  labels:
    app: priceguard-api
data:
  PORT: "8080"
  GIN_MODE: "release"
  
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "priceguard"
  DB_USER: "priceguard_user"
  DB_SSL_MODE: "require"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Performance Configuration
  DB_MAX_OPEN_CONNS: "50"
  DB_MAX_IDLE_CONNS: "25"
  DB_CONN_MAX_LIFETIME: "1h"
  
  REDIS_POOL_SIZE: "50"
  REDIS_MIN_IDLE_CONNS: "20"
  REDIS_MAX_IDLE_CONNS: "40"
  
  # HTTP Configuration
  HTTP_READ_TIMEOUT: "10s"
  HTTP_WRITE_TIMEOUT: "10s"
  HTTP_IDLE_TIMEOUT: "120s"
  HTTP_MAX_CONNS_PER_IP: "200"
  
  # WebSocket Configuration
  WS_MAX_CONNECTIONS: "50000"
  WS_MAX_CONNECTIONS_PER_IP: "50"
  WS_BROADCAST_WORKERS: "20"
  
  # Alert Engine Configuration
  ALERT_MAX_WORKERS: "25"
  ALERT_QUEUE_SIZE: "5000"
  ALERT_MAX_CONCURRENT_EVALUATIONS: "100"
  
  # Cache Configuration
  CACHE_DEFAULT_TTL: "1h"
  CACHE_PRICE_TTL: "1m"
  CACHE_SESSION_TTL: "24h"
  CACHE_MEMORY_SIZE: "1000"
  CACHE_ENABLE_WARMING: "true"
  
  # Rate Limiting
  RATE_LIMIT_RPS: "500"
  RATE_LIMIT_BURST: "1000"
  RATE_LIMIT_WINDOW: "1m"
  
  # Monitoring
  METRICS_ENABLED: "true"
  METRICS_PORT: "8081"
  HEALTH_CHECK_ENABLED: "true"
  
  # JWT Configuration
  JWT_EXPIRATION: "24h"
  
  # External APIs
  BINANCE_API_URL: "https://api.binance.com"
  BINANCE_WS_URL: "wss://stream.binance.com:9443"
  
  # Google OAuth
  GOOGLE_OAUTH_REDIRECT_URL: "https://api.priceguard.io/auth/callback"

---
apiVersion: v1
kind: Secret
metadata:
  name: priceguard-secrets
  namespace: priceguard
  labels:
    app: priceguard-api
type: Opaque
stringData:
  # Database Credentials
  DB_PASSWORD: "your-secure-db-password"
  
  # Redis Password
  REDIS_PASSWORD: "your-secure-redis-password"
  
  # JWT Secret
  JWT_SECRET: "your-super-secure-jwt-secret-key-here"
  
  # Google OAuth Credentials
  GOOGLE_CLIENT_ID: "your-google-oauth-client-id"
  GOOGLE_CLIENT_SECRET: "your-google-oauth-client-secret"
  
  # Binance API Credentials
  BINANCE_API_KEY: "your-binance-api-key"
  BINANCE_API_SECRET: "your-binance-api-secret"
  
  # Email Configuration
  SMTP_PASSWORD: "your-smtp-password"
  
  # External Service Keys
  NOTIFICATION_SERVICE_KEY: "your-notification-service-key"
