apiVersion: v1
kind: Secret
metadata:
  name: priceguard-secrets
  namespace: priceguard
type: Opaque
stringData:
  jwt-secret: "your-super-secret-jwt-key-here"
  db-password: "your-secure-db-password"
  redis-password: "your-secure-redis-password"
  google-client-secret: "your-google-oauth-client-secret"
  binance-api-secret: "your-binance-api-secret"
  grafana-admin-password: "secure-grafana-password"

---
apiVersion: v1
kind: Secret
metadata:
  name: priceguard-tls
  namespace: priceguard
type: kubernetes.io/tls
data:
  tls.crt: # Base64 encoded certificate
  tls.key: # Base64 encoded private key
